[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python','python3']

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = ['python','python3']

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python','python3']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript','jquery']
