export HISTFILE="$MYENV"/.zsh_history
export HISTSIZE=1000
export SAVEHIST=100000
setopt hist_ignore_dups

function codels (){
  clear
  grep -nrIe $1 ./
}

. /etc/zsh_command_not_found

activate="${ZDOTDIR}/activate"

if [ ! -z "${activate}" ]; then
  . $activate
fi
